#!/usr/bin/env python3
"""Turn Support/logo/touchgrass-mark.svg into the generated LogoMarkData.swift files.

The mark is a designer SVG: a flat list of <path d="…" fill="#rrggbb"/> in paint order.
Nothing in the app can load an SVG (no third-party deps, and TGMenuBar / TGOverlay must not
share code), so the path data is baked into a Swift literal per module and parsed at runtime
by each module's SVGPathParser.

Run:  python3 Support/logo/svg2swift.py

Writes (identical content, module-internal each time):
    Sources/TGMenuBar/LogoMarkData.swift
    Sources/TGOverlay/LogoMarkData.swift

Support/icon/generate.swift does NOT use these — being a standalone script it reads the SVG
directly, with the same parser inlined.
"""

import os
import re
import sys
from xml.etree import ElementTree

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SVG = os.path.join(ROOT, "Support", "logo", "touchgrass-mark.svg")
TARGETS = [
    os.path.join(ROOT, "Sources", "TGMenuBar", "LogoMarkData.swift"),
    os.path.join(ROOT, "Sources", "TGOverlay", "LogoMarkData.swift"),
]

SVG_NS = "{http://www.w3.org/2000/svg}"


def hex_to_rgb(value):
    value = value.strip().lstrip("#")
    if len(value) == 3:
        value = "".join(c * 2 for c in value)
    if len(value) != 6:
        raise SystemExit("unsupported fill %r — only #rgb / #rrggbb" % value)
    return tuple(int(value[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def collect(svg_path):
    """Every <path> in document (= paint) order, as (d, (r, g, b))."""
    tree = ElementTree.parse(svg_path)
    root = tree.getroot()

    view_box = root.get("viewBox")
    if not view_box:
        raise SystemExit("the SVG has no viewBox")
    box = [float(n) for n in re.split(r"[\s,]+", view_box.strip())]
    if len(box) != 4:
        raise SystemExit("malformed viewBox %r" % view_box)

    shapes = []
    for element in root.iter(SVG_NS + "path"):
        d = element.get("d")
        if not d:
            continue
        fill = element.get("fill")
        if fill is None:
            # An inherited fill would need real CSS cascade; the designer file has none.
            style = element.get("style") or ""
            match = re.search(r"fill\s*:\s*([^;]+)", style)
            fill = match.group(1) if match else "#000000"
        if fill.strip().lower() == "none":
            continue
        shapes.append((" ".join(d.split()), hex_to_rgb(fill)))

    if not shapes:
        raise SystemExit("no filled <path> elements found")
    return box, shapes


def swift_source(box, shapes, svg_name):
    lines = [
        "// Generated by Support/logo/svg2swift.py from Support/logo/%s — do not edit." % svg_name,
        "// Re-run:  python3 Support/logo/svg2swift.py",
        "import CoreGraphics",
        "",
        "/// The TouchGrass mark: %d filled paths in paint order, in the SVG's own coordinates" % len(shapes),
        "/// (y down, origin top-left). `SVGPathParser` turns `d` into a `CGPath`;",
        "/// `LogoMarkGeometry` maps them into whatever rect is being drawn.",
        "enum LogoMarkData {",
        "",
        "    /// One `<path>`: its `d` attribute and its flat fill, in sRGB 0…1.",
        "    struct Shape {",
        "        let d: String",
        "        let fill: (r: CGFloat, g: CGFloat, b: CGFloat)",
        "    }",
        "",
        "    /// The SVG's viewBox.",
        "    static let viewBox = CGRect(x: %s, y: %s, width: %s, height: %s)"
        % tuple(("%g" % v) for v in box),
        "",
        "    /// Back to front, exactly the SVG's document order.",
        "    static let shapes: [Shape] = [",
    ]
    for d, (r, g, b) in shapes:
        lines.append('        Shape(d: "%s",' % d.replace("\\", "\\\\").replace('"', '\\"'))
        lines.append("              fill: (%.5f, %.5f, %.5f))," % (r, g, b))
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main():
    box, shapes = collect(SVG)
    source = swift_source(box, shapes, os.path.basename(SVG))
    for target in TARGETS:
        with open(target, "w") as handle:
            handle.write(source)
        print("wrote %s (%d paths)" % (os.path.relpath(target, ROOT), len(shapes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
